name: Build EPUB via Docker Compose

on:
  push:
    paths:
      - '**/*'
    branches:
      - main

jobs:
  build-epub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose to build EPUB
        run: |
          docker compose run book-builder

      # Optional: Upload the EPUB file as an artifact
      - name: Upload first EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: epub_first_book
          path: my-ebook/cpp_low_latency.epub # <-- Update this to your actual EPUB file path

      # Optional: Upload the EPUB file as an artifact
      - name: Upload second EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: epub_second_book
          path: my-ebook/cpp_low_latency2.epub # <-- Update this to your actual EPUB file path


  validate-epub:
    runs-on: ubuntu-latest
    needs: build-epub
    steps:
      - name: Download EPUB artifact
        uses: actions/download-artifact@v4
        with:
          name: epub_first_book
          path: ./epub-artifacts

      - name: Download the other EPUB artifact
        uses: actions/download-artifact@v4
        with:
          name: epub_second_book
          path: ./epub-artifacts

      - name: Download epubcheck
        run: |
          wget https://github.com/w3c/epubcheck/releases/download/v5.0.0/epubcheck-5.0.0.zip
          unzip epubcheck-5.0.0.zip

      - name: Run epubcheck on first book
        run: |
          java -jar epubcheck-5.0.0/epubcheck.jar ./epub-artifacts/cpp_low_latency.epub

      - name: Run epubcheck on second book
        run: |
          java -jar epubcheck-5.0.0/epubcheck.jar ./epub-artifacts/cpp_low_latency2.epub
